"""Init

Revision ID: 75a7b563278a
Revises: cd3bcaa053e2
Create Date: 2023-06-01 21:53:40.640154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a7b563278a'
down_revision = 'cd3bcaa053e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
