"""Init

Revision ID: 8c70d4d5ca43
Revises: 75a7b563278a
Create Date: 2023-06-02 10:37:39.974700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c70d4d5ca43'
down_revision = '75a7b563278a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
