"""Init

Revision ID: d5b8a2653334
Revises: 8c70d4d5ca43
Create Date: 2023-06-02 11:10:47.757464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b8a2653334'
down_revision = '8c70d4d5ca43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
