"""Init

Revision ID: d7b2be0f5329
Revises: d5b8a2653334
Create Date: 2023-06-03 17:05:34.358236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b2be0f5329'
down_revision = 'd5b8a2653334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('teachers', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    # ### end Alembic commands ###
